### ISSUE TITLE
Issue with stillstatuscompleted case

### ISSUE THREAD

**Issue by srikanthmunaga** [MadKudu/node-marketo#57]
tried to use statustillcomplteted work flow and it not coming out the flow in the till completed case and giving the promise errors can you please help me on this.

Here is the error i am getting:

reason is {"requestId":"79bb#16494e58f06","errors":[{"code":"606"}]}
Possibly unhandled TypeError: Illegal invocation, resolver resolve/reject must be called within a resolver context. Consider using the promise constructor instead.
    at PromiseResolver$reject (F:\marketo\node_modules\node-marketo-rest\node_modules\bluebird\js\main\promise_resolver.js:118:15)
    at tryCatch1 (F:\marketo\node_modules\node-marketo-rest\node_modules\bluebird\js\main\util.js:45:21)
    at Promise$_callHandler [as _callHandler] (F:\marketo\node_modules\node-marketo-rest\node_modules\bluebird\js\main\promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (F:\marketo\node_modules\node-marketo-rest\node_modules\bluebird\js\main\promise.js:675:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (F:\marketo\node_modules\node-marketo-rest\node_modules\bluebird\js\main\promise.js:845:14)
    at Promise$_settlePromises [as _settlePromises] (F:\marketo\node_modules\node-marketo-rest\node_modules\bluebird\js\main\promise.js:988:14)
    at Promise$_rejectPromises [as _rejectPromises] (F:\marketo\node_modules\node-marketo-rest\node_modules\bluebird\js\main\promise.js:981:10)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (F:\marketo\node_modules\node-marketo-rest\node_modules\bluebird\js\main\async.js:77:12)
    at Async$consumeFunctionBuffer (F:\marketo\node_modules\node-marketo-rest\node_modules\bluebird\js\main\async.js:40:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

**Comment by miguelHx** [comment]
Need more context, can you provide the arguments and method that you used to produce this error?
